app_port: 8000
frontend_url: http://localhost:3000
migrates_folder: migrations
enable_telemetry: true
clamav_url: clamav:3310
conf_db:
  address: dbPostgres
  port: 5559
  user: aHAjeK
  pass: AOifjwelmc8dw
  db_name: lazarus
  max_connections: 10
auth:
  supabase_url: https://abc.supabase.co
  supabase_anon: abcdefghijklmnopqrstuvwxyz0123456789
  callback_url: http://localhost:8080/auth/callback
  frontend_url: http://localhost:3000
  cookie_domain:
  # cookie_secure: 1 for production, 0 for development
  cookie_secure: 0
  cookie_same_site: lax
  mode: development
s3:
  region: hel1
  endpoint: https://abc.hel1.your-objectstorage.com
  bucket: abc
  access_key_id: ACCESS_KEY
  secret_access_key: SECRET_KEY
  prefix: dev/
  use_path_style: false
  max_upload_size_bytes: 1024
